name: taxibrunei
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  country_code_picker: ^3.0.0
  flutter_credit_card: ^4.0.0
  flutter_polyline_points: ^2.0.0
  flutter_typeahead: ^4.0.0
  font_awesome_flutter: ^10.0.0
  geolocator: ^10.0.0
  google_fonts: ^6.0.0
  google_maps_flutter: ^2.5.0
  http: ^1.2.1
  pin_code_fields: ^8.0.0
  provider: ^6.0.5
  share: ^2.0.4
  smooth_star_rating: ^1.1.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
