name: green_taxi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  country_code_picker: ^2.0.2
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  google_fonts: ^6.0.0
  font_awesome_flutter: ^10.6.0
  flutter_typeahead: ^4.3.7
  uuid: ^3.0.7
  provider: ^6.0.5
  http: ^1.2.0
  flutter_polyline_points: ^1.0.0
  share: ^2.0.4
  flutter_credit_card: ^3.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/taxilogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
